#!/usr/bin/env bash
#
# Helper script for analyzing obfuscation output logs
# generated by `obfuscate_corpus.sh`.

if [ "$1" == "" ]; then
    echo "USAGE: $(basename $0) LOG_DIR [SKIP_NO_GOAL]" >&2
    exit 1
fi

LOG_DIR="$(realpath "$1")"
SKIP_NO_GOAL="$2"

i=0
total_depth=0
total_cost=0
total_runtime=0
total_length=0
num_skipped=0

HORIZ="+-------+---------+---------------+------------+--------------+----------+"

echo "$HORIZ"
printf "| %5s | %7s | %13s | %10s | %12s | %8s |\n" "Case" "Depth" "Cost" "Runtime" "Length Ratio" "Has Goal"
echo "$HORIZ"

for case_log in "$LOG_DIR"/*.log; do
    case="$(basename "$case_log" | cut -d"." -f1)"
    depth=$(($(grep -oP "(?<=Depth: )\d+" "$case_log" | tail -n1) - 1))
    runtime="$(grep -oP "(?<=Runtime: )\d+" "$case_log" | tail -n1)"
    length="$(grep -oP "(?<=Text Length Ratio: )\d+\.\d+" "$case_log" | tail -n1)"
    cost="$(grep -oP "(?<=g\(x\):)\s+\d+\.\d+" "$case_log" | awk '{ print $1 }' | tail -n1)"

    if ! grep -q "==== GOAL STATE: ====" "$case_log"; then
        has_goal="N"
    else
        has_goal="Y"
    fi

    printf "| %5s | %7s | %13s | %10s | %12s | %8s |\n" "${case}" "${depth}" "${cost}" "${runtime}s" "${length}" "${has_goal}"

    if [ "$has_goal" != "Y" ] && [ "$SKIP_NO_GOAL" != "" ]; then
        num_skipped=$(($num_skipped + 1))
    else
        i=$(($i + 1))
        total_depth=$(echo "$total_depth + $depth" | bc -l)
        total_runtime=$(echo "$total_runtime + $runtime" | bc -l)
        total_length=$(echo "$total_length + $length" | bc -l)
        total_cost=$(echo "$total_cost + $cost" | bc -l)
    fi
done
echo "$HORIZ"

echo
echo "Average depth: $(echo "scale=2; ${total_depth} / ${i}" | bc -l)"
echo "Average runtime: $(echo "scale=2; ${total_runtime} / ${i}" | bc -l)s"
echo "Average text length ratio: $(echo "scale=2; ${total_length} / ${i}" | bc -l)"
echo "Average cost: $(echo "scale=2; ${total_cost} / ${i}" | bc -l)"
if [ "$SKIP_NO_GOAL" != "" ]; then
    echo "Cases with no goal skipped: ${num_skipped}"
fi
